version: "3"
services:

  auth:
    image: postgres:15
    container_name: auth
    restart: always
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ufc123
    ports:
      - 5434:5432

  product:
    image: postgres:15
    container_name: product
    restart: always
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=ufc123
    ports:
      - 5435:5432

  sales_db:
    image: mongo:latest
    container_name: sales_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=ufc123
    ports:
      - 27017:27017

  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080

  product-api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=ufc123
    ports:
      - 5672:5672
      - 15672:15672