server:
  port: ${PORT:8081}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/product
    username: admin  # Nota: Garanta que o user no Docker realmente seja admin (ou mude para postgres)
    password: ufc123
    hikari:
      maximum-pool-size: 3 # Substitui o antigo maxActive de forma moderna

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true     # Nota: Mudou de show_sql para show-sql (hífen)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:admin}
    password: ${RABBIT_MQ_PASSWORD:ufc123}

app-config:
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}

  rabbit:
    exchange:
      product: product.topic

    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey

    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
