INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1001, 'Comic Books');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1003, 'Books');

INSERT INTO SUPPLIER (ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO SUPPLIER (ID, NAME) VALUES (1002, 'Amazon');

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (1001, 'Crise nas infinitas terras', 1001, 1001, 10);

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (1002, 'Interistelar', 1002, 1002, 5);

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (1003, 'Shrek 2', 1002, 1002, 3);

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (1004, 'A morte de Ivan Ilitch', 1003, 1002, 8);